/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2015-03-15 09:47:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertEmp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Emp</title>\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7; IE=EmulateIE9\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" media=\"all\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"demo.css\" media=\"all\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<!--/ freshdesignweb top bar -->\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<h1> Enter Employee Details to Insert</h1>\r\n");
      out.write("            </header>       \r\n");
      out.write("      <div  class=\"form\" >\r\n");
      out.write("    \t\t<form id=\"contactform\" action=\"InsertEmpServlet\"> \r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<!-- \t<p class=\"contact\"><label for=\"name\">Employee Number</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"Emp no\" placeholder=\"Enter Employee Number\" required=\"\"  type=\"text\">  -->\r\n");
      out.write("    \t\t\t \r\n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"name\">Employee Name</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"Empname\" placeholder=\"Enter Employee Name\" required=\"\" type=\"text\"> \r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"name\">Employee Skill</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"Empskill\" placeholder=\"Enter Employee Skill\" required=\"\" type=\"text\"> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <p class=\"contact\"><label for=\"name\">Employee Projectdescription</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"Empprodesc\" placeholder=\"Enter Employee Projectdescription\" required=\"\" type=\"text\"> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <p class=\"contact\"><label for=\"name\">Hiredate</label></p> \r\n");
      out.write("    \t\t\t<input id=\"date\" name=\"Hiredate\" placeholder=\"Enter Hiredate\" required=\"\" type=\"text\"> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <p class=\"contact\"><label for=\"name\">Manager Name</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"ManagerName\" placeholder=\"Enter Manager Name\" required=\"\" type=\"text\"> \r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"name\">Department Number</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"Deptno\" placeholder=\"Enter Department Number\" required=\"\" type=\"text\"> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <p class=\"contact\"><label for=\"name\">UserId</label></p> \r\n");
      out.write("    \t\t\t<input id=\"name\" name=\"Userid\" placeholder=\"Enter UserId\" required=\"\" type=\"text\"> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\t\t\r\n");
      out.write("            <p class=\"contact\"><label for=\"name\">Password</label></p> \r\n");
      out.write("            <input id=\"name\" name=\"Pswd\" placeholder=\"Enter PasswordLocation\" required=\"\" type=\"text\"> <br>\r\n");
      out.write("            \r\n");
      out.write("            <p class=\"contact\"><label for=\"name\">CreatedUserid</label></p> \r\n");
      out.write("            <input id=\"name\" name=\"cuid\" placeholder=\"Enter CreatedUserid\" required=\"\" type=\"text\"> <br>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("            <input class=\"buttom\" name=\"submit\" id=\"submit\" tabindex=\"5\" value=\"Submit\" type=\"submit\"> \r\n");
      out.write("            <input class=\"buttom\" name=\"submit\" id=\"cancel\" value=\"Cancel\" type=\"button\">  \t \t \r\n");
      out.write("   </form> \r\n");
      out.write("</div>  \r\n");
      out.write("    \r\n");
 session.setAttribute("username",session.getAttribute("username")); 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$('#cancel').click(function(){\r\n");
      out.write("\t\twindow.location.replace(\"AddOrSearchEmp.jsp\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");

String obj =(String) request.getAttribute("successFlag");
if(obj!=null){
	if(obj.equals("success")){

      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<h2 style=\"color: red;font: 50\">Record Sucessfully Inserted</h2>\r\n");
      out.write("</center>\r\n");
}}
      out.write("\r\n");
      out.write(" -->   \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
